name: Setup puppeteer
description: Install Chromium

runs:
  using: composite
  steps:
    - name: Get installed Puppeteer version
      shell: bash
      id: puppeteer-version
      run: echo "PUPPETEER_VERSION=$(node -p "require('./package.json').dependencies.puppeteer || require('./package.json').devDependencies.puppeteer || ''")" >> $GITHUB_OUTPUT
    - uses: actions/cache@v4
      name: Setup puppeteer cache
      id: puppeteer-cache
      with:
        path: ${{ env.PUPPETEER_CACHE_DIRECTORY }}
        key: ${{ runner.os }}-puppeteer-${{ steps.puppeteer-version.outputs.PUPPETEER_VERSION }}
        restore-keys: |
          ${{ runner.os }}-puppeteer-
      env:
        PUPPETEER_CACHE_DIRECTORY: "/home/runner/.cache/puppeteer"
    - name: Install Chrome
      run: |
        if ${{ steps.puppeteer-cache.outputs.cache-hit != 'true' }}; then
          pnpm install
          pnpm run install:chrome
        fi
      shell: bash
