name: 定期実行

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */8 * * *'

jobs:
  run-parallel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [1, 0]
      max-parallel: 2
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm-dev \
            libxkbcommon-dev \
            libgbm-dev \
            libasound2-dev
            
      - name: chromium
        uses: ./.github/actions/chrome
        
      - name: Dependency installing
        run: pnpm i
        
      - name: Run TYPE=${{ matrix.type }}
        run: TYPEID=${{ matrix.type }} npm start
        env:
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"
