name: 定期実行

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */8 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      # Chromiumの依存関係をインストール
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm-dev \
            libxkbcommon-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libxss-dev \
            libasound2-dev
            
      - name: chromium
        uses: ./.github/actions/chrome
        
      - name: Dependency installing
        run: pnpm i
        
      - name: Run TYPE=1
        run: TYPEID=1 npm start
        env:
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"
          
      - name: Run TYPE=0
        run: TYPEID=0 npm start
        env:
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"
