name: 定期実行

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */8 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      # システム依存関係のキャッシュ
      - name: Cache system dependencies
        id: cache-system-deps
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: system-deps-${{ runner.os }}-${{ hashFiles('.github/workflows/**') }}
          
      # Chromiumの依存関係をインストール（キャッシュがない場合のみ）
      - name: Install Chromium dependencies
        if: steps.cache-system-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm-dev \
            libxkbcommon-dev \
            libxcomposite-dev \
            libxdamage-dev \
            libxrandr-dev \
            libgbm-dev \
            libxss-dev \
            libasound2-dev
            
      - name: Debug - Check cache key
        run: |
          echo "Puppeteer version: $(node -p "require('./package.json').dependencies.puppeteer || require('./package.json').devDependencies.puppeteer || ''")"
          
      - name: chromium
        uses: ./.github/actions/chrome
        
      - name: Debug - Check if cache was hit
        run: |
          echo "Cache directory exists: $(ls -la /home/runner/.cache/puppeteer/ 2>/dev/null || echo 'No')"
          echo "Chrome binary exists: $(find /home/runner/.cache/puppeteer/ -name "chrome" -type f 2>/dev/null || echo 'No')"
        
      - name: Dependency installing
        run: pnpm i
        
      - name: Run TYPE=1
        run: TYPEID=1 npm start
        env:
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"
          
      - name: Run TYPE=0
        run: TYPEID=0 npm start
        env:
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"
