name: 定期実行

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 */8 * * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Install Chromium dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libnss3-dev libatk-bridge2.0-dev libdrm-dev \
            libxkbcommon-dev libgbm-dev libasound2-dev
            
      - name: chromium
        uses: ./.github/actions/chrome
        
      - name: Dependency installing
        run: pnpm i
        
      # セットアップ完了後、workspace全体をアーティファクトとして保存
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            .
            ~/.cache/puppeteer
          retention-days: 1

  run-tasks:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [1, 0]
      max-parallel: 2
      
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
          
      - name: Restore Puppeteer cache
        run: |
          if [ -d "home/runner/.cache/puppeteer" ]; then
            sudo mkdir -p /home/runner/.cache
            sudo cp -r home/runner/.cache/puppeteer /home/runner/.cache/
          fi
          
      - name: Set up Node 24 (minimal)
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          
      - name: Install pnpm (minimal)
        uses: pnpm/action-setup@v4
        with:
          version: 9
          
      - name: Run TYPE=${{ matrix.type }}
        run: TYPEID=${{ matrix.type }} npm start
        env:
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage"
